### ISSUE TITLE
Introduce a `singleton` function

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [foretagsplatsen/objectjs#10]
I think it should be easy, enforce the usage of the pattern, 
and help to go around the inheritance issue we currently have.

It could also ease the path if/when we change class instantiation

**Comment by NicolasPetton** [comment]
Wouldn't it be a bit weird to have `singleton` on `object` and all subclasses? Or maybe I'm misunderstanding you.

**Comment by BenjaminVanRyseghem** [comment]
the idea is to have it as we have `subclass`

like

```js
var animalFactory = object.singleton(function(that, my){});
```

That will generate a new class that is a singleton pattern implementation

**Comment by NicolasPetton** [comment]
> var animalFactory = object.singleton(function(that, my){});

I like the idea, but when I read your example I think you're retrieving
the singleton of the object class.

**Comment by BenjaminVanRyseghem** [comment]
we can see the naming :smile:

but usually in a singleton pattern, you do not call a specific method to get the instance :smile:

P.S.: check your phone! I texted you 1h ago :wink:

**Comment by NicolasPetton** [comment]
> but usually in a singleton pattern, you do not call a specific method
> to get the instance :smile:

You usually have a class-side method (`instance', `singleton', etc.) to
retrieve the instance of the class, or do I misunderstand something?

**Comment by BenjaminVanRyseghem** [comment]
indeed, that's a way to do it :smile:

then I do not know how to name it

**Comment by NicolasPetton** [comment]
> then I do not know how to name it

How 'bout the ugly `singletonSubclass`? :D
