### ISSUE TITLE
Escape characters

### ISSUE THREAD

**Issue by DamienCassou** [foretagsplatsen/objectjs#21]
![screenshot from 2016-09-22 17-50-04](https://cloud.githubusercontent.com/assets/217543/18755572/0f71e7a0-80ed-11e6-9a57-500519112bcc.png)

**Comment by DamienCassou** [comment]
Wrong repo, sorry.

**Comment by NicolasPetton** [comment]
I think this is unrelated, but anyway here's what I get

![screenshot from 2016-09-22 17-51-48](https://cloud.githubusercontent.com/assets/123539/18755653/53b45074-80ed-11e6-8b4e-b9396c677c0e.png)

**Comment by BenjaminVanRyseghem** [comment]
WTF?

**Comment by DamienCassou** [comment]
@BenjaminVanRyseghem @NicolasPetton https://github.com/NicolasPetton/gulp-task-runner/issues/1

**Comment by BenjaminVanRyseghem** [comment]
how is that related to objectjs? Am I missing a point?

**Comment by DamienCassou** [comment]
@BenjaminVanRyseghem please read https://github.com/foretagsplatsen/objectjs/issues/21#issuecomment-248944850

**Comment by BenjaminVanRyseghem** [comment]
@DamienCassou why https://github.com/foretagsplatsen/objectjs/issues/21#issuecomment-248948399 then?
