### ISSUE TITLE
add travis support

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [foretagsplatsen/objectjs#4]
(and maybe move to npm instead of bower)

**Comment by NicolasPetton** [comment]
> (and maybe move to npm instead of bower)

Since we currently use bower, I'd add support for both.

**Comment by BenjaminVanRyseghem** [comment]
that's a fresh repo, bower is dying.

I would not bother

**Comment by NicolasPetton** [comment]
> I would not bother

But we use Bower in the client, wouldn't it be weird to start mixing
things?

**Comment by BenjaminVanRyseghem** [comment]
I think we are not discussing the same thing.

objectjs could be exposed as a bower package so that we can load it.

But my point was more about objectjs itself, which load dependences using bower, where I think npm is more the way to go nowadays :smile:

**Comment by NicolasPetton** [comment]
Benjamin Van Ryseghem <notifications@github.com> writes:

> But my point was more about objectjs itself, which load dependences
> using bower, where I think npm is more the way to go nowadays :smile:

Ahah, I see what you mean now, and I totally agree!

**Comment by BenjaminVanRyseghem** [comment]
done!
